### ISSUE TITLE
컴플렉스 트랜스포즈(*) 에러

### ISSUE THREAD

**Issue by physimatics** [freshrimpsushi/admin#2]
\psi^{*} 라고 쓰면 아래와 같이 개판나고 \psi^{\ast}라고 써야 잘 나온다.
![image](https://user-images.githubusercontent.com/70989305/104686602-e2d40000-5740-11eb-9133-beb1dad5b0b8.png)

**Comment by physimatics** [comment]
이게 문제가 아니었고 갑자기 해결됐는데 왜 됐는지를 모름;

**Comment by rmsmsgood** [comment]
그것 참 다행입니다
