### ISSUE TITLE
영문병기인데 볼드체가 아닌 경우 에러

### ISSUE THREAD

**Issue by physimatics** [freshrimpsushi/admin#3]
![image](https://user-images.githubusercontent.com/70989305/104687579-d5b81080-5742-11eb-9680-32ac9d1a380c.png)
![image](https://user-images.githubusercontent.com/70989305/104687614-e799b380-5742-11eb-9abf-b736a080746e.png)

![image](https://user-images.githubusercontent.com/70989305/104687626-ebc5d100-5742-11eb-8940-03974755af97.png)
![image](https://user-images.githubusercontent.com/70989305/104687658-f97b5680-5742-11eb-85e6-34b58c651d4c.png)

**Comment by rmsmsgood** [comment]
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ca4cc6b5-0787-4988-a5b1-661acc60247e/Untitled.png]
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ea4e7908-ec56-4dd3-be0f-55bf8e0f956b/Untitled.png]

노션에 보고된 경우랑 같은데 일단 이 기능을 빼면 됨. 그리고 문서 관리의 측면에서도 말 그대로 수식이 아닌 곳에 수식을 쓰려고 했다가 생긴 문제라서 이번 리뉴얼을 기점으로 텍은 최소한만 쓰는게 권장됨.

일단 크롤러에서 니 표준에 맞추는 기능은 삭제하도록 하겠음
