### ISSUE TITLE
타이포라에서 \&인데 휴고로 넘어가면서 \가 사라지는 문제 #1720

### ISSUE THREAD

**Issue by physimatics** [freshrimpsushi/admin#5]
![image](https://user-images.githubusercontent.com/70989305/104796463-ccd64600-57f9-11eb-9e87-593b59498a51.png)

![image](https://user-images.githubusercontent.com/70989305/104796485-0c9d2d80-57fa-11eb-8422-528b2d8afe70.png)

타이포라에서 \\&라고 입력했을 때 블로그 수식코드 까봤을 때 \&로 나옴.
\&인 경우 &로 나옴.
& 앞에 \가 하나 사라져버림.

**Comment by physimatics** [comment]
노션에 있던 두 문서가 둘 다 & 때문에 생기는 문제였음.

**Comment by rmsmsgood** [comment]
그냥 수작업 하기로 함
