### ISSUE TITLE
이해 안되는 _{} 문제   #1702

### ISSUE THREAD

**Issue by physimatics** [freshrimpsushi/admin#6]
![image](https://user-images.githubusercontent.com/70989305/104796898-94d10200-57fd-11eb-8e59-866ba9f97ea4.png)
![image](https://user-images.githubusercontent.com/70989305/104796918-b7fbb180-57fd-11eb-91cd-a788ef75b9dd.png)

위 두 사진을 비교해보면 분명 교집합 기호 \bigcap 와 아래첨자 _{\alpha} 사이에 띄어쓰기가 있냐 없냐의 차이로 렌더링이 되냐 안되냐가 결정됨. 그래서 띄어쓰기가 문제인가 싶었더니

![image](https://user-images.githubusercontent.com/70989305/104796976-14f76780-57fe-11eb-8edf-33c972fee6f3.png)
한 개씩 해보면 미친 그것도 아님.

![image](https://user-images.githubusercontent.com/70989305/104797000-348e9000-57fe-11eb-8ee5-ba749b365e39.png)
\left( \right) 문제도 아님.

![image](https://user-images.githubusercontent.com/70989305/104797089-d6ae7800-57fe-11eb-87d4-bf9e43ed3e1f.png)
아래첨자가 총 4개 있는데 빨간색 박스로 친 부분만 띄어쓰기 있을 때 렌더링 오류남.

**Comment by rmsmsgood** [comment]
이건 나도 따로 발견했는데 조건이 뭐가됐든 일단 ' _{'를 '_{'으로 바꾸는건 해야하는듯함. 다는 아니라도 어느정도 고쳐질 예정

**Comment by rmsmsgood** [comment]
이것도 그럼 집합 기호 문제가 아니라 _ 문제인것같음
