### ISSUE TITLE
집합기호 버그 #1718

### ISSUE THREAD

**Issue by physimatics** [freshrimpsushi/admin#9]
![image](https://user-images.githubusercontent.com/70989305/104798940-4c6e1000-580e-11eb-9b61-44f053bba060.png)

------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/70989305/104798960-67408480-580e-11eb-8d84-f8f54ff78bb5.png)

$\left\\{ \mathbf{x}_{n} \right\\}$가 뒤의 글과 한 줄에 있으면 렌더링 에러가 나고 다른 줄에 있으면 멀쩡함

**Comment by rmsmsgood** [comment]
![image](https://user-images.githubusercontent.com/47377298/104799350-de2b4c80-5811-11eb-8058-b1d4ed6425fe.png)

뭔 문젠진 모르겠는데 'E_{N}' 얘가 문제인것같음

**Comment by rmsmsgood** [comment]
```
$\left\\{ \mathbf{x}_{n} \right\\}$ 를 $\mathbb{R}^{k}$ 에서 코시 수열이라고 하자. $E_N$ 을 증명 $(b)$ 에서와 같은 것이라고 하자. 그러면 
```
E_{N} 을 E_N 으로 고치니까 아래와 같이 나옴. 잘 보면 _ 사이사이가 이탤릭체로 기울어져 있을텐데 내가 보기엔 집합 기호가 문제가 아니라 _가 문제를 일으키는 중임

![image](https://user-images.githubusercontent.com/47377298/104799423-56920d80-5812-11eb-8cf5-fd37cf76260a.png)

**Comment by rmsmsgood** [comment]
![image](https://user-images.githubusercontent.com/47377298/104799455-9a851280-5812-11eb-981a-c2bf1d89952a.png)

이탤릭에 싸먹히는듯...

**Comment by rmsmsgood** [comment]
https://discourse.gohugo.io/t/disable-underscore-for-italic-text/24512

**Comment by rmsmsgood** [comment]
이건 hugo 차원에서 _로 하는 이탤릭을 금지시키는 방안을 찾아보는식으로 극복해야할듯

**Comment by physimatics** [comment]
![image](https://user-images.githubusercontent.com/70989305/104799515-04052100-5813-11eb-9d85-a9e97b3201c5.png)

같은 문단에서 집합기호 텍코드가 나오기 이전에 _{}가 있는경우 렌더링이 정상적으로 됨.

**Comment by rmsmsgood** [comment]
``` <- 이거 써서 렌더링 전은 어떤지도 같이 병기해주셈

**Comment by rmsmsgood** [comment]
https://bwaycer.github.io/hugo_tutorial.hugo/tutorials/mathjax/#issues-with-markdown

https://stackoverflow.com/questions/53587872/markdown-latex-driving-me-crazy-with-hugo-on-github

_를 \_로 매핑하는 방법밖에 없는듯. 이거랑 같이 오토텍도 고치면 되겠네... ㅠ
